version: "3.8"

services:
  django:
    build:
      context: ./images/django
    image: django
    container_name: django
    restart: always
    networks:
      - transcendance
    command: python3 images/django/mysite/back/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - vuejs

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
        - transcendance
    volumes:
      - postgres:/var/lib/postgresql/data/
    restart: always

  vuejs:
    build:
      context: ./images/vuejs
    image: vuejs
    container_name: vuejs
    restart: always
    networks:
      - transcendance
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres:

networks:
  transcendance:
    driver: bridge
    name: transcendance
