version: "3.8"

services:
  django:
    build:
      context: ./images/django
    image: django
    container_name: django
    restart: always
    command: python3 images/django/mysite/back/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/
     
volumes:
  postgres:
