# Generated by Django 4.2.7 on 2024-01-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=14, null=True, unique=True, verbose_name='username')),
                ('password', models.CharField(null=True, verbose_name='password')),
                ('pfp', models.ImageField(null=True, upload_to='pfp', verbose_name='pfp')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('wins', models.IntegerField(default=0, verbose_name='wins')),
                ('losses', models.IntegerField(default=0, verbose_name='losses')),
                ('twoFA', models.BooleanField(default=False, verbose_name='twoFA')),
                ('language', models.IntegerField(default=1, verbose_name='language')),
                ('elo', models.PositiveIntegerField(default=200, verbose_name='elo')),
                ('best_elo', models.PositiveIntegerField(default=200, verbose_name='best_elo')),
                ('best_rank', models.PositiveIntegerField(default=2147483647, verbose_name='best_rank')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=True, verbose_name='name')),
                ('description', models.CharField(default='', verbose_name='description')),
                ('capacity', models.IntegerField(default=16, verbose_name='capacity')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='back_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='back_api.user')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='back_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(null=True, verbose_name='nickname')),
                ('position', models.IntegerField(null=True, verbose_name='position')),
                ('status', models.IntegerField(default=True, verbose_name='status')),
                ('stage', models.IntegerField(default=0, verbose_name='stage')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='back_api.tournament')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='back_api.user')),
            ],
        ),
    ]
