# Generated by Django 4.2.7 on 2024-01-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(null=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email'),
        ),
    ]
