# Generated by Django 4.2.7 on 2024-01-23 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0004_user_key_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remote_bool',
            field=models.BooleanField(default=False, verbose_name='remote_bool'),
        ),
        migrations.AddField(
            model_name='user',
            name='remote_token',
            field=models.CharField(default='', verbose_name='remote_token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='best_elo',
            field=models.PositiveIntegerField(default=500, verbose_name='best_elo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='elo',
            field=models.PositiveIntegerField(default=500, verbose_name='elo'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=14, null=True, verbose_name='guest')),
                ('hostscore', models.IntegerField(default=0, verbose_name='host')),
                ('guestscore', models.IntegerField(default=0, verbose_name='guest')),
                ('date', models.CharField(default='2042-42-42', verbose_name='date')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
